name: projectionClustering
channels:
  - conda-forge
  - dloewenstein
  - defaults
dependencies:
  - r-uwot
  - jupyterlab
  - ca-certificates
  - openssl
  - rise
  - r-irkernel
  - certifi
  - r-factominer
  - r-microbenchmark
  - r-kernlab
  - r-dbscan
